### ISSUE TITLE
[Bug]: Validator Key Stats on Validator Client Only Setup

### ISSUE THREAD

**Issue by daGscheid** [stereum-dev/ethereum-node#1207] opened 2023-04-30 10:03 UTC
### Contact Details

-----

### Describe the bug!

If a stereum node only runs a Validator Client, the staking page seems broken. 

### Attach a Screenshot!

![example](https://user-images.githubusercontent.com/82385103/235347096-806be4a6-da21-4b8d-9016-d1c8efcea63c.png)

These should be active validators, they show no data

### Expected Behaviour

I expected the Validator Keys to get a status regardless, if the others clients are installed or not, even though I know why this isn't working currently (haha).  

### Help us reproduce your bug!

Here is how to reproduce it!

-> Set up multiple Nodes, connect them externally
-> Set up one of the Nodes with only a Validator Client
-> Import the Validator Clients Keys 
-> Status doesn't change, when attesting.  

### Launcher Version

2.0.0-rc.17

### Desktop OS

Mac

### Node Server OS

Ubuntu 22.04

### Affected Service

-------

### Relevant log output

```shell
------
```

### Acknowledgment

- [X] I looked through the existing bugs of this project

**Comment by NeoPlays** [comment] 2023-06-07 10:38
caused by wrong setup. closing for now

**Closed by NeoPlays** 2023-06-07 10:38 UTC
Labels: bug
